### ISSUE TITLE
Feature: `RETURN` statement documentation page

### ISSUE THREAD

**Issue by gander** [surrealdb/www.surrealdb.com#257]
### Is your feature request related to a problem?

Why is this statement nowhere described as a standalone command? It would make it much easier for me to test commands if the effect of their operation would be returned to me right away.

### Describe the solution

Prepare a subpage for `RETURN`.

https://surrealdb.com/docs/surrealql/functions/script/surrealql-functions

### Alternative methods

Write on another subpage that you can use `RETURN`. Not nearly at the end of the documentation.

### SurrealDB version

1.0.0-beta.9+20230402.5eafebd for linux on x86_64

### Contact Details

cpa108pa@duck.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
This would be because the `RETURN` is a clause that can be used within statements as can be seen here https://surrealdb.com/docs/surrealql/statements/relate. 

I don't think we will document it as a standalone statement, what can do though is highlight it's usage a bit more. I'd have to think of where in the docs this will fit. Open to any suggestions.

**Comment by kearfy** [comment]
@Ekwuno I think there is a miscommunication. You are referring to the `RETURN` keyword which can be used within various CRUD operations, while @gander is talking about the actual `RETURN` statement. We will add this to the documentation, I never even realised this was not yet documented!
