### ISSUE TITLE
Improve open graph social media sharing

### ISSUE THREAD

**Issue by AlexFrid** [surrealdb/www.surrealdb.com#90]
Would be good to improve the open graph social media sharing previews

When sharing the geo functions page https://surrealdb.com/docs/surrealql/functions/geo

It just gave a general title for both title and description
![image](https://user-images.githubusercontent.com/11931107/229182118-afa0f613-1e95-4212-94de-2faeeca4a9ca.png)

What I expected was:

SurrealDB | Geo functions
These functions can be used when working with and analysing geospatial data.

https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/

**Comment by MatthewAry** [comment]
Would be really helpful when having multiple tabs open to know what page I am on.
![image](https://github.com/surrealdb/www.surrealdb.com/assets/157217/48c97b54-6ad4-4f7b-a67d-77e1269f2446)
Because I can't tell what tab is on what page, even though I am trying to string together a whole bunch of different things to make my SurrealQL queries.

**Comment by tobiemh** [comment]
This should now be fixed with the launch of the new documentation site: https://docs.surrealdb.com 🚀 !
